# Autogenerated wrapper script for viterbi_jll for aarch64-apple-darwin
export libviterbi

JLLWrappers.@generate_wrapper_header("viterbi")
JLLWrappers.@declare_library_product(libviterbi, "@rpath/libviterbi.dylib")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libviterbi,
        "lib/libviterbi.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
